# Generated by Django 6.0.1 on 2026-01-30 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('part_code', models.CharField(max_length=60)),
                ('tep_code', models.CharField(max_length=60)),
                ('part_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.JSONField(default=dict)),
                ('material_part_code', models.CharField(max_length=80)),
                ('material_name', models.CharField(blank=True, max_length=160, null=True)),
                ('unit', models.CharField(choices=[('pc', 'pc'), ('pcs', 'pcs'), ('m', 'm')], max_length=10)),
                ('dim_qty', models.FloatField()),
                ('loss_percent', models.FloatField(default=10.0)),
                ('total', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='app.customer')),
            ],
        ),
    ]
