# Generated by Django 6.0.1 on 2026-02-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='qty',
            new_name='dim_qty',
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('pc', 'PC'), ('pcs', 'PCS'), ('m', 'M')], max_length=10),
        ),
    ]
