# Generated by Django 6.0.1 on 2026-02-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_qty_material_dim_qty_alter_material_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_partcode', models.CharField(max_length=80, unique=True)),
                ('mat_partname', models.CharField(max_length=160)),
                ('mat_maker', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('pc', 'PC'), ('pcs', 'PCS'), ('m', 'M')], max_length=10)),
            ],
        ),
    ]
