# Generated by Django 6.0.1 on 2026-02-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_materiallist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('pc', 'pc'), ('pcs', 'pcs'), ('m', 'm')], max_length=10),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='unit',
            field=models.CharField(choices=[('pc', 'pc'), ('pcs', 'pcs'), ('m', 'm')], max_length=10),
        ),
    ]
