# Generated by Django 6.0.1 on 2026-02-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('pc', 'pc'), ('pcs', 'pcs'), ('m', 'm'), ('g', 'g')], max_length=10),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='unit',
            field=models.CharField(choices=[('pc', 'pc'), ('pcs', 'pcs'), ('m', 'm'), ('g', 'g')], max_length=10),
        ),
    ]
