# Generated by Django 6.0.1 on 2026-02-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_employeeprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('pc', 'pc'), ('pcs', 'pcs'), ('m', 'm'), ('g', 'g'), ('kg', 'kg')], max_length=10),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='unit',
            field=models.CharField(choices=[('pc', 'pc'), ('pcs', 'pcs'), ('m', 'm'), ('g', 'g'), ('kg', 'kg')], max_length=10),
        ),
    ]
